// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/waveprotocol/box/contact/contacts.proto

package org.waveprotocol.box.contact;

public final class ContactsProto {
  private ContactsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContactRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 timestamp = 1;
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp of previous response or 0.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp of previous response or 0.
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code contacts.ContactRequest}
   */
  public static final class ContactRequest extends
      com.google.protobuf.GeneratedMessage
      implements ContactRequestOrBuilder {
    // Use ContactRequest.newBuilder() to construct.
    private ContactRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ContactRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ContactRequest defaultInstance;
    public static ContactRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ContactRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ContactRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.waveprotocol.box.contact.ContactsProto.ContactRequest.class, org.waveprotocol.box.contact.ContactsProto.ContactRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ContactRequest> PARSER =
        new com.google.protobuf.AbstractParser<ContactRequest>() {
      public ContactRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ContactRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp of previous response or 0.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp of previous response or 0.
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.waveprotocol.box.contact.ContactsProto.ContactRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contacts.ContactRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.waveprotocol.box.contact.ContactsProto.ContactRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.waveprotocol.box.contact.ContactsProto.ContactRequest.class, org.waveprotocol.box.contact.ContactsProto.ContactRequest.Builder.class);
      }

      // Construct using org.waveprotocol.box.contact.ContactsProto.ContactRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactRequest_descriptor;
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactRequest getDefaultInstanceForType() {
        return org.waveprotocol.box.contact.ContactsProto.ContactRequest.getDefaultInstance();
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactRequest build() {
        org.waveprotocol.box.contact.ContactsProto.ContactRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactRequest buildPartial() {
        org.waveprotocol.box.contact.ContactsProto.ContactRequest result = new org.waveprotocol.box.contact.ContactsProto.ContactRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.waveprotocol.box.contact.ContactsProto.ContactRequest) {
          return mergeFrom((org.waveprotocol.box.contact.ContactsProto.ContactRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.waveprotocol.box.contact.ContactsProto.ContactRequest other) {
        if (other == org.waveprotocol.box.contact.ContactsProto.ContactRequest.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.waveprotocol.box.contact.ContactsProto.ContactRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.waveprotocol.box.contact.ContactsProto.ContactRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 timestamp = 1;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp of previous response or 0.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp of previous response or 0.
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp of previous response or 0.
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp of previous response or 0.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:contacts.ContactRequest)
    }

    static {
      defaultInstance = new ContactRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:contacts.ContactRequest)
  }

  public interface ContactResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 timestamp = 1;
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp.
     * </pre>
     */
    long getTimestamp();

    // repeated .contacts.ContactResponse.Contact contact = 2;
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> 
        getContactList();
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact getContact(int index);
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    int getContactCount();
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    java.util.List<? extends org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder> 
        getContactOrBuilderList();
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder getContactOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code contacts.ContactResponse}
   */
  public static final class ContactResponse extends
      com.google.protobuf.GeneratedMessage
      implements ContactResponseOrBuilder {
    // Use ContactResponse.newBuilder() to construct.
    private ContactResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ContactResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ContactResponse defaultInstance;
    public static ContactResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ContactResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ContactResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                contact_ = new java.util.ArrayList<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact>();
                mutable_bitField0_ |= 0x00000002;
              }
              contact_.add(input.readMessage(org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          contact_ = java.util.Collections.unmodifiableList(contact_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.waveprotocol.box.contact.ContactsProto.ContactResponse.class, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ContactResponse> PARSER =
        new com.google.protobuf.AbstractParser<ContactResponse>() {
      public ContactResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ContactResponse> getParserForType() {
      return PARSER;
    }

    public interface ContactOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string participant = 1;
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      boolean hasParticipant();
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      java.lang.String getParticipant();
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      com.google.protobuf.ByteString
          getParticipantBytes();

      // required double score = 2;
      /**
       * <code>required double score = 2;</code>
       *
       * <pre>
       * Score of coontact to sort list.
       * </pre>
       */
      boolean hasScore();
      /**
       * <code>required double score = 2;</code>
       *
       * <pre>
       * Score of coontact to sort list.
       * </pre>
       */
      double getScore();
    }
    /**
     * Protobuf type {@code contacts.ContactResponse.Contact}
     */
    public static final class Contact extends
        com.google.protobuf.GeneratedMessage
        implements ContactOrBuilder {
      // Use Contact.newBuilder() to construct.
      private Contact(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Contact(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Contact defaultInstance;
      public static Contact getDefaultInstance() {
        return defaultInstance;
      }

      public Contact getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Contact(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                participant_ = input.readBytes();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                score_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_Contact_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.class, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder.class);
      }

      public static com.google.protobuf.Parser<Contact> PARSER =
          new com.google.protobuf.AbstractParser<Contact>() {
        public Contact parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Contact(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Contact> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string participant = 1;
      public static final int PARTICIPANT_FIELD_NUMBER = 1;
      private java.lang.Object participant_;
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      public boolean hasParticipant() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      public java.lang.String getParticipant() {
        java.lang.Object ref = participant_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            participant_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string participant = 1;</code>
       *
       * <pre>
       * The address of caller in email format.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getParticipantBytes() {
        java.lang.Object ref = participant_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          participant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required double score = 2;
      public static final int SCORE_FIELD_NUMBER = 2;
      private double score_;
      /**
       * <code>required double score = 2;</code>
       *
       * <pre>
       * Score of coontact to sort list.
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double score = 2;</code>
       *
       * <pre>
       * Score of coontact to sort list.
       * </pre>
       */
      public double getScore() {
        return score_;
      }

      private void initFields() {
        participant_ = "";
        score_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasParticipant()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasScore()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getParticipantBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, score_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getParticipantBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, score_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code contacts.ContactResponse.Contact}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_Contact_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_Contact_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.class, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder.class);
        }

        // Construct using org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          participant_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_Contact_descriptor;
        }

        public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact getDefaultInstanceForType() {
          return org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.getDefaultInstance();
        }

        public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact build() {
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact buildPartial() {
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact result = new org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.participant_ = participant_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.score_ = score_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact) {
            return mergeFrom((org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact other) {
          if (other == org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.getDefaultInstance()) return this;
          if (other.hasParticipant()) {
            bitField0_ |= 0x00000001;
            participant_ = other.participant_;
            onChanged();
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasParticipant()) {
            
            return false;
          }
          if (!hasScore()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string participant = 1;
        private java.lang.Object participant_ = "";
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public boolean hasParticipant() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public java.lang.String getParticipant() {
          java.lang.Object ref = participant_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            participant_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public com.google.protobuf.ByteString
            getParticipantBytes() {
          java.lang.Object ref = participant_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            participant_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public Builder setParticipant(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          participant_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public Builder clearParticipant() {
          bitField0_ = (bitField0_ & ~0x00000001);
          participant_ = getDefaultInstance().getParticipant();
          onChanged();
          return this;
        }
        /**
         * <code>required string participant = 1;</code>
         *
         * <pre>
         * The address of caller in email format.
         * </pre>
         */
        public Builder setParticipantBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          participant_ = value;
          onChanged();
          return this;
        }

        // required double score = 2;
        private double score_ ;
        /**
         * <code>required double score = 2;</code>
         *
         * <pre>
         * Score of coontact to sort list.
         * </pre>
         */
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double score = 2;</code>
         *
         * <pre>
         * Score of coontact to sort list.
         * </pre>
         */
        public double getScore() {
          return score_;
        }
        /**
         * <code>required double score = 2;</code>
         *
         * <pre>
         * Score of coontact to sort list.
         * </pre>
         */
        public Builder setScore(double value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double score = 2;</code>
         *
         * <pre>
         * Score of coontact to sort list.
         * </pre>
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:contacts.ContactResponse.Contact)
      }

      static {
        defaultInstance = new Contact(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:contacts.ContactResponse.Contact)
    }

    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     *
     * <pre>
     * Timestamp.
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // repeated .contacts.ContactResponse.Contact contact = 2;
    public static final int CONTACT_FIELD_NUMBER = 2;
    private java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> contact_;
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    public java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> getContactList() {
      return contact_;
    }
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    public java.util.List<? extends org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder> 
        getContactOrBuilderList() {
      return contact_;
    }
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    public int getContactCount() {
      return contact_.size();
    }
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact getContact(int index) {
      return contact_.get(index);
    }
    /**
     * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
     *
     * <pre>
     * Contact list.
     * </pre>
     */
    public org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder getContactOrBuilder(
        int index) {
      return contact_.get(index);
    }

    private void initFields() {
      timestamp_ = 0L;
      contact_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getContactCount(); i++) {
        if (!getContact(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      for (int i = 0; i < contact_.size(); i++) {
        output.writeMessage(2, contact_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      for (int i = 0; i < contact_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, contact_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.contact.ContactsProto.ContactResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.waveprotocol.box.contact.ContactsProto.ContactResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contacts.ContactResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.waveprotocol.box.contact.ContactsProto.ContactResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.waveprotocol.box.contact.ContactsProto.ContactResponse.class, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Builder.class);
      }

      // Construct using org.waveprotocol.box.contact.ContactsProto.ContactResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContactFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          contactBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.waveprotocol.box.contact.ContactsProto.internal_static_contacts_ContactResponse_descriptor;
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactResponse getDefaultInstanceForType() {
        return org.waveprotocol.box.contact.ContactsProto.ContactResponse.getDefaultInstance();
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactResponse build() {
        org.waveprotocol.box.contact.ContactsProto.ContactResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.waveprotocol.box.contact.ContactsProto.ContactResponse buildPartial() {
        org.waveprotocol.box.contact.ContactsProto.ContactResponse result = new org.waveprotocol.box.contact.ContactsProto.ContactResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (contactBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            contact_ = java.util.Collections.unmodifiableList(contact_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.contact_ = contact_;
        } else {
          result.contact_ = contactBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.waveprotocol.box.contact.ContactsProto.ContactResponse) {
          return mergeFrom((org.waveprotocol.box.contact.ContactsProto.ContactResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.waveprotocol.box.contact.ContactsProto.ContactResponse other) {
        if (other == org.waveprotocol.box.contact.ContactsProto.ContactResponse.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (contactBuilder_ == null) {
          if (!other.contact_.isEmpty()) {
            if (contact_.isEmpty()) {
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureContactIsMutable();
              contact_.addAll(other.contact_);
            }
            onChanged();
          }
        } else {
          if (!other.contact_.isEmpty()) {
            if (contactBuilder_.isEmpty()) {
              contactBuilder_.dispose();
              contactBuilder_ = null;
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000002);
              contactBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContactFieldBuilder() : null;
            } else {
              contactBuilder_.addAllMessages(other.contact_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getContactCount(); i++) {
          if (!getContact(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.waveprotocol.box.contact.ContactsProto.ContactResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.waveprotocol.box.contact.ContactsProto.ContactResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 timestamp = 1;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp.
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp.
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       *
       * <pre>
       * Timestamp.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // repeated .contacts.ContactResponse.Contact contact = 2;
      private java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> contact_ =
        java.util.Collections.emptyList();
      private void ensureContactIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contact_ = new java.util.ArrayList<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact>(contact_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder, org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder> contactBuilder_;

      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> getContactList() {
        if (contactBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contact_);
        } else {
          return contactBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public int getContactCount() {
        if (contactBuilder_ == null) {
          return contact_.size();
        } else {
          return contactBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact getContact(int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);
        } else {
          return contactBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder setContact(
          int index, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.set(index, value);
          onChanged();
        } else {
          contactBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder setContact(
          int index, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder addContact(org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(value);
          onChanged();
        } else {
          contactBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder addContact(
          int index, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(index, value);
          onChanged();
        } else {
          contactBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder addContact(
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder addContact(
          int index, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder addAllContact(
          java.lang.Iterable<? extends org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact> values) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          super.addAll(values, contact_);
          onChanged();
        } else {
          contactBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          contactBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public Builder removeContact(int index) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.remove(index);
          onChanged();
        } else {
          contactBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder getContactBuilder(
          int index) {
        return getContactFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder getContactOrBuilder(
          int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);  } else {
          return contactBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public java.util.List<? extends org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder> 
           getContactOrBuilderList() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contact_);
        }
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder addContactBuilder() {
        return getContactFieldBuilder().addBuilder(
            org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder addContactBuilder(
          int index) {
        return getContactFieldBuilder().addBuilder(
            index, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .contacts.ContactResponse.Contact contact = 2;</code>
       *
       * <pre>
       * Contact list.
       * </pre>
       */
      public java.util.List<org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder> 
           getContactBuilderList() {
        return getContactFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder, org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact, org.waveprotocol.box.contact.ContactsProto.ContactResponse.Contact.Builder, org.waveprotocol.box.contact.ContactsProto.ContactResponse.ContactOrBuilder>(
                  contact_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:contacts.ContactResponse)
    }

    static {
      defaultInstance = new ContactResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:contacts.ContactResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contacts_ContactRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contacts_ContactRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contacts_ContactResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contacts_ContactResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contacts_ContactResponse_Contact_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contacts_ContactResponse_Contact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+org/waveprotocol/box/contact/contacts." +
      "proto\022\010contacts\"#\n\016ContactRequest\022\021\n\ttim" +
      "estamp\030\001 \002(\003\"\207\001\n\017ContactResponse\022\021\n\ttime" +
      "stamp\030\001 \002(\003\0222\n\007contact\030\002 \003(\0132!.contacts." +
      "ContactResponse.Contact\032-\n\007Contact\022\023\n\013pa" +
      "rticipant\030\001 \002(\t\022\r\n\005score\030\002 \002(\001B-\n\034org.wa" +
      "veprotocol.box.contactB\rContactsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_contacts_ContactRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_contacts_ContactRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contacts_ContactRequest_descriptor,
              new java.lang.String[] { "Timestamp", });
          internal_static_contacts_ContactResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_contacts_ContactResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contacts_ContactResponse_descriptor,
              new java.lang.String[] { "Timestamp", "Contact", });
          internal_static_contacts_ContactResponse_Contact_descriptor =
            internal_static_contacts_ContactResponse_descriptor.getNestedTypes().get(0);
          internal_static_contacts_ContactResponse_Contact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contacts_ContactResponse_Contact_descriptor,
              new java.lang.String[] { "Participant", "Score", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
