// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/waveprotocol/box/searches/searches.proto

package org.waveprotocol.box.searches;

public final class SearchesProto {
  private SearchesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .searches.SearchesItem search = 1;
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem> 
        getSearchList();
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    org.waveprotocol.box.searches.SearchesProto.SearchesItem getSearch(int index);
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    int getSearchCount();
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    java.util.List<? extends org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder> 
        getSearchOrBuilderList();
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder getSearchOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code searches.Searches}
   */
  public static final class Searches extends
      com.google.protobuf.GeneratedMessage
      implements SearchesOrBuilder {
    // Use Searches.newBuilder() to construct.
    private Searches(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Searches(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Searches defaultInstance;
    public static Searches getDefaultInstance() {
      return defaultInstance;
    }

    public Searches getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Searches(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                search_ = new java.util.ArrayList<org.waveprotocol.box.searches.SearchesProto.SearchesItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              search_.add(input.readMessage(org.waveprotocol.box.searches.SearchesProto.SearchesItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          search_ = java.util.Collections.unmodifiableList(search_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_Searches_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_Searches_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.waveprotocol.box.searches.SearchesProto.Searches.class, org.waveprotocol.box.searches.SearchesProto.Searches.Builder.class);
    }

    public static com.google.protobuf.Parser<Searches> PARSER =
        new com.google.protobuf.AbstractParser<Searches>() {
      public Searches parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Searches(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Searches> getParserForType() {
      return PARSER;
    }

    // repeated .searches.SearchesItem search = 1;
    public static final int SEARCH_FIELD_NUMBER = 1;
    private java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem> search_;
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    public java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem> getSearchList() {
      return search_;
    }
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    public java.util.List<? extends org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder> 
        getSearchOrBuilderList() {
      return search_;
    }
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    public int getSearchCount() {
      return search_.size();
    }
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    public org.waveprotocol.box.searches.SearchesProto.SearchesItem getSearch(int index) {
      return search_.get(index);
    }
    /**
     * <code>repeated .searches.SearchesItem search = 1;</code>
     */
    public org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder getSearchOrBuilder(
        int index) {
      return search_.get(index);
    }

    private void initFields() {
      search_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getSearchCount(); i++) {
        if (!getSearch(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < search_.size(); i++) {
        output.writeMessage(1, search_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < search_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, search_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.Searches parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.waveprotocol.box.searches.SearchesProto.Searches prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code searches.Searches}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.waveprotocol.box.searches.SearchesProto.SearchesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_Searches_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_Searches_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.waveprotocol.box.searches.SearchesProto.Searches.class, org.waveprotocol.box.searches.SearchesProto.Searches.Builder.class);
      }

      // Construct using org.waveprotocol.box.searches.SearchesProto.Searches.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSearchFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (searchBuilder_ == null) {
          search_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          searchBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_Searches_descriptor;
      }

      public org.waveprotocol.box.searches.SearchesProto.Searches getDefaultInstanceForType() {
        return org.waveprotocol.box.searches.SearchesProto.Searches.getDefaultInstance();
      }

      public org.waveprotocol.box.searches.SearchesProto.Searches build() {
        org.waveprotocol.box.searches.SearchesProto.Searches result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.waveprotocol.box.searches.SearchesProto.Searches buildPartial() {
        org.waveprotocol.box.searches.SearchesProto.Searches result = new org.waveprotocol.box.searches.SearchesProto.Searches(this);
        int from_bitField0_ = bitField0_;
        if (searchBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            search_ = java.util.Collections.unmodifiableList(search_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.search_ = search_;
        } else {
          result.search_ = searchBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.waveprotocol.box.searches.SearchesProto.Searches) {
          return mergeFrom((org.waveprotocol.box.searches.SearchesProto.Searches)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.waveprotocol.box.searches.SearchesProto.Searches other) {
        if (other == org.waveprotocol.box.searches.SearchesProto.Searches.getDefaultInstance()) return this;
        if (searchBuilder_ == null) {
          if (!other.search_.isEmpty()) {
            if (search_.isEmpty()) {
              search_ = other.search_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSearchIsMutable();
              search_.addAll(other.search_);
            }
            onChanged();
          }
        } else {
          if (!other.search_.isEmpty()) {
            if (searchBuilder_.isEmpty()) {
              searchBuilder_.dispose();
              searchBuilder_ = null;
              search_ = other.search_;
              bitField0_ = (bitField0_ & ~0x00000001);
              searchBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSearchFieldBuilder() : null;
            } else {
              searchBuilder_.addAllMessages(other.search_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSearchCount(); i++) {
          if (!getSearch(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.waveprotocol.box.searches.SearchesProto.Searches parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.waveprotocol.box.searches.SearchesProto.Searches) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .searches.SearchesItem search = 1;
      private java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem> search_ =
        java.util.Collections.emptyList();
      private void ensureSearchIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          search_ = new java.util.ArrayList<org.waveprotocol.box.searches.SearchesProto.SearchesItem>(search_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.waveprotocol.box.searches.SearchesProto.SearchesItem, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder, org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder> searchBuilder_;

      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem> getSearchList() {
        if (searchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(search_);
        } else {
          return searchBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public int getSearchCount() {
        if (searchBuilder_ == null) {
          return search_.size();
        } else {
          return searchBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public org.waveprotocol.box.searches.SearchesProto.SearchesItem getSearch(int index) {
        if (searchBuilder_ == null) {
          return search_.get(index);
        } else {
          return searchBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder setSearch(
          int index, org.waveprotocol.box.searches.SearchesProto.SearchesItem value) {
        if (searchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSearchIsMutable();
          search_.set(index, value);
          onChanged();
        } else {
          searchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder setSearch(
          int index, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder builderForValue) {
        if (searchBuilder_ == null) {
          ensureSearchIsMutable();
          search_.set(index, builderForValue.build());
          onChanged();
        } else {
          searchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder addSearch(org.waveprotocol.box.searches.SearchesProto.SearchesItem value) {
        if (searchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSearchIsMutable();
          search_.add(value);
          onChanged();
        } else {
          searchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder addSearch(
          int index, org.waveprotocol.box.searches.SearchesProto.SearchesItem value) {
        if (searchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSearchIsMutable();
          search_.add(index, value);
          onChanged();
        } else {
          searchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder addSearch(
          org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder builderForValue) {
        if (searchBuilder_ == null) {
          ensureSearchIsMutable();
          search_.add(builderForValue.build());
          onChanged();
        } else {
          searchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder addSearch(
          int index, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder builderForValue) {
        if (searchBuilder_ == null) {
          ensureSearchIsMutable();
          search_.add(index, builderForValue.build());
          onChanged();
        } else {
          searchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder addAllSearch(
          java.lang.Iterable<? extends org.waveprotocol.box.searches.SearchesProto.SearchesItem> values) {
        if (searchBuilder_ == null) {
          ensureSearchIsMutable();
          super.addAll(values, search_);
          onChanged();
        } else {
          searchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder clearSearch() {
        if (searchBuilder_ == null) {
          search_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          searchBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public Builder removeSearch(int index) {
        if (searchBuilder_ == null) {
          ensureSearchIsMutable();
          search_.remove(index);
          onChanged();
        } else {
          searchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder getSearchBuilder(
          int index) {
        return getSearchFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder getSearchOrBuilder(
          int index) {
        if (searchBuilder_ == null) {
          return search_.get(index);  } else {
          return searchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public java.util.List<? extends org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder> 
           getSearchOrBuilderList() {
        if (searchBuilder_ != null) {
          return searchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(search_);
        }
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder addSearchBuilder() {
        return getSearchFieldBuilder().addBuilder(
            org.waveprotocol.box.searches.SearchesProto.SearchesItem.getDefaultInstance());
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder addSearchBuilder(
          int index) {
        return getSearchFieldBuilder().addBuilder(
            index, org.waveprotocol.box.searches.SearchesProto.SearchesItem.getDefaultInstance());
      }
      /**
       * <code>repeated .searches.SearchesItem search = 1;</code>
       */
      public java.util.List<org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder> 
           getSearchBuilderList() {
        return getSearchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.waveprotocol.box.searches.SearchesProto.SearchesItem, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder, org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder> 
          getSearchFieldBuilder() {
        if (searchBuilder_ == null) {
          searchBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.waveprotocol.box.searches.SearchesProto.SearchesItem, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder, org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder>(
                  search_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          search_ = null;
        }
        return searchBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:searches.Searches)
    }

    static {
      defaultInstance = new Searches(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:searches.Searches)
  }

  public interface SearchesItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string query = 2;
    /**
     * <code>required string query = 2;</code>
     */
    boolean hasQuery();
    /**
     * <code>required string query = 2;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>required string query = 2;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();
  }
  /**
   * Protobuf type {@code searches.SearchesItem}
   */
  public static final class SearchesItem extends
      com.google.protobuf.GeneratedMessage
      implements SearchesItemOrBuilder {
    // Use SearchesItem.newBuilder() to construct.
    private SearchesItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SearchesItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SearchesItem defaultInstance;
    public static SearchesItem getDefaultInstance() {
      return defaultInstance;
    }

    public SearchesItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SearchesItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              query_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_SearchesItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_SearchesItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.waveprotocol.box.searches.SearchesProto.SearchesItem.class, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder.class);
    }

    public static com.google.protobuf.Parser<SearchesItem> PARSER =
        new com.google.protobuf.AbstractParser<SearchesItem>() {
      public SearchesItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchesItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SearchesItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string query = 2;
    public static final int QUERY_FIELD_NUMBER = 2;
    private java.lang.Object query_;
    /**
     * <code>required string query = 2;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string query = 2;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string query = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
      query_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getQueryBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getQueryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.waveprotocol.box.searches.SearchesProto.SearchesItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.waveprotocol.box.searches.SearchesProto.SearchesItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code searches.SearchesItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.waveprotocol.box.searches.SearchesProto.SearchesItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_SearchesItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_SearchesItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.waveprotocol.box.searches.SearchesProto.SearchesItem.class, org.waveprotocol.box.searches.SearchesProto.SearchesItem.Builder.class);
      }

      // Construct using org.waveprotocol.box.searches.SearchesProto.SearchesItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.waveprotocol.box.searches.SearchesProto.internal_static_searches_SearchesItem_descriptor;
      }

      public org.waveprotocol.box.searches.SearchesProto.SearchesItem getDefaultInstanceForType() {
        return org.waveprotocol.box.searches.SearchesProto.SearchesItem.getDefaultInstance();
      }

      public org.waveprotocol.box.searches.SearchesProto.SearchesItem build() {
        org.waveprotocol.box.searches.SearchesProto.SearchesItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.waveprotocol.box.searches.SearchesProto.SearchesItem buildPartial() {
        org.waveprotocol.box.searches.SearchesProto.SearchesItem result = new org.waveprotocol.box.searches.SearchesProto.SearchesItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.query_ = query_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.waveprotocol.box.searches.SearchesProto.SearchesItem) {
          return mergeFrom((org.waveprotocol.box.searches.SearchesProto.SearchesItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.waveprotocol.box.searches.SearchesProto.SearchesItem other) {
        if (other == org.waveprotocol.box.searches.SearchesProto.SearchesItem.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasQuery()) {
          bitField0_ |= 0x00000002;
          query_ = other.query_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasQuery()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.waveprotocol.box.searches.SearchesProto.SearchesItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.waveprotocol.box.searches.SearchesProto.SearchesItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required string query = 2;
      private java.lang.Object query_ = "";
      /**
       * <code>required string query = 2;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string query = 2;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string query = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string query = 2;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 2;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000002);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 2;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        query_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:searches.SearchesItem)
    }

    static {
      defaultInstance = new SearchesItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:searches.SearchesItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_searches_Searches_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_searches_Searches_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_searches_SearchesItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_searches_SearchesItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,org/waveprotocol/box/searches/searches" +
      ".proto\022\010searches\"2\n\010Searches\022&\n\006search\030\001" +
      " \003(\0132\026.searches.SearchesItem\"+\n\014Searches" +
      "Item\022\014\n\004name\030\001 \002(\t\022\r\n\005query\030\002 \002(\tB.\n\035org" +
      ".waveprotocol.box.searchesB\rSearchesProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_searches_Searches_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_searches_Searches_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_searches_Searches_descriptor,
              new java.lang.String[] { "Search", });
          internal_static_searches_SearchesItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_searches_SearchesItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_searches_SearchesItem_descriptor,
              new java.lang.String[] { "Name", "Query", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
